repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.0
  hooks:
  - id: isort
    name: isort (python)

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    files: '\.py$'
    args: [--config, setup.cfg]    

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    files: '\.py$'
    args: # arguments to configure black
      - --line-length=88
