name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test it
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}
