# This workflow will build the docker image and push to GitHub Container Registry

name: Production Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  commit_files:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: project/version.py
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Create Pipfile.lock
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install pipenv
          pipenv lock
      -
        name: Version
        run: |
          touch $VERSION_FILE
          VERSION=${{ github.ref_name }}
          echo "VERSION = '${VERSION:1}'" > $VERSION_FILE
      -
        name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":rocket: Add Pipfile.lock, version.py for release `${{ github.ref_name }}` [ci skip]"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: Pipfile.lock ${{ env.VERSION_FILE }}
          add_options: '--force'
          create_branch: false
      -
        name: Remove tag
        run: |
          git push --delete origin ${{ github.ref_name }}
      -
        name: Retag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.ref_name }}
          tag_prefix: ""
      -
        name: Create a GitHub release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}      

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/rsginc/noodling
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
