name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  get_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "branch=dev" >> $GITHUB_ENV
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}

      - name: test it
        run: echo ${{ env.branch }}
