name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  get_branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch_name.outputs.branch }}
    steps:
      - name: Set branch name
        id: branch_name
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=dev" >> $GITHUB_OUTPUT
          fi

  commit:
    runs-on: ubuntu-latest
    needs: get_branch
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.get_branch.outputs.branch }}
          
      - name: create empty file
        run: touch test.py
        
      - name: commit back
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "this is a test"
          branch: ${{ needs.get_branch.outputs.branch }}
          file_pattern: test.py
          create_branch: false
