name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          
      - name: create empty file
        run: touch test.py
        
      - name: commit back
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "this is a test"
          branch: ${{ github.ref_name }}
          file_pattern: test.py
          create_branch: false
